#! /bin/sh
function usage()
{
	cat <<EOF
Usage: config-libhash [OPTION]
Available values for OPTION include:

        --cc        C compiler
        --cxx       C++ compiler
        --cflags    pre-processor and compiler flags
        --help      display this help and exit
        --libs      library linking information
        --prefix    libhash install prefix
        --version   output version information
EOF
	exit $1
}

if test $# -eq 0; then
	usage 1
fi

while test $# -gt 0; do
	case "$1" in
	--cc) 
		echo gcc 
		;;
	--cxx) 
		echo g++ 
		;;
	--prefix) 
		echo /home/ronald/opt
		;;
	--version)
		echo libhash 1.3
		;;
	--help)
		usage 0
		;;
	--cflags)
		if [ ! -z `echo /home/ronald/opt | sed -e 's#^/usr##'` ]; then
			echo -n "-I/home/ronald/opt${prefix}/include"
		fi
		echo " `config-swing --cflags`"
		;;
	--libs)
		if [ ! -z `echo /home/ronald/opt | sed -e 's#^/usr##'` ]; then
			echo -n "-L/home/ronald/opt${exec_prefix}/lib -Wl,--rpath,/home/ronald/opt${exec_prefix}/lib "
		fi
		echo -n "-lhash"
		echo " `config-swing --libs`"
		;;
	*)
		echo unknown option $1
		exit 1
		;;
	esac
	shift
done
